ボウリングスコア計算プログラム作成
hongfu22/ruby-practices pull request #5
Opened 2021-09-10 00:07 UTC by hongfu22

ボウリングのスコア計算プログラムを作成しました。

2021-09-16 01:54 UTC, u1tnk requested changes
だいたい大丈夫なのですが、ちょっと強引に処理しているところがあるので、整理できると良いと思います 💪

2021-09-16 01:54 UTC, u1tnk commented on 04.bowling/bowling.rb
> +while frames.size > 10
ここの処理は読みときづらいですね。
whileなので、frames全てを処理するのかな？と思ったのと、rubyでwhileをほぼ見ないのもあってちょっと混乱しました。
あと、framesの数に依存する処理をframesの中でやるのが危険というのもあって、ミスがあって減らせないと無限ループになっちゃうのも良くないですね。

そのままのロジックでより安全な書き方にするならこんな感じかなあ 🤔 

```
temp_frames  = [] # 名前が微妙ですが、新しい配列に一回移した方が安全なのでその下で `tmp`は微妙と書いたのですが、ここは本当に一時保存だけなので良いかなと。

12.times do |i| # 最終が全部ストライクの場合最大数
  if i < 9
     temp_frames << frames[i]
  else 
     temp_frames[9] += frames[i]
  end
end
frames = temp_frames
```

もうちょっとオススメは
`frames[9..]`
で配列のindex9以降全部が取れるので、それをまとめて frames[9]に代入する形ですね。
それならループも一時変数も不要なので。

一番良いのは、最初から10フレームしか作らないように分割の方を工夫する事ですが、それは応用編なので、こちらの修正でもどちらでも大丈夫です 🙆‍♀️

2021-09-16 01:54 UTC, u1tnk commented on 04.bowling/bowling.rb
> +def strike_cal(game_index, game_array)
細かいのですが、メソッド名は 動詞が先の方が自然になりますし、少しなら省略しない方が伝わりやすいので、`calc_strike_score`/`calc_score_when_strike`とかの方が良いかと思います。後者はさすがに長いかもしれませんが、分かりやすさが大事なんです 😅

2021-09-16 23:27 UTC, hongfu22 commented
ご指摘いただきありがとうございます。
while文の箇所をframes[9..]
関数名を修正してみました。
大変お手数ですが再度ご確認いただけますと幸いです。

2021-09-17 00:29 UTC, u1tnk approved these changes

2023-07-12 04:29 UTC, merged